name: waterfox-snap # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '56.2.14' # just for humans, typically '1.2+git' or '1.3.2'
summary: Browse the web YOUR way # 79 char long summary
description: |
  Waterfox focuses on giving users choice. The browser is focused on power
  users, which lets you make the important decisions. There is no plugin whitelist 
  (meaning you can run Java Applets and Silverlight apps), you can run whichever
  extensions you like (including bootstrapped add-ons that can completely change 
  functionality of the browser) and absolutely no data or telemetry is sent back
  to Mozilla or the Waterfox project.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  desktop-gtk:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    # make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - libgtk-3-bin
      - unity-gtk2-module
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk
      - ibus-gtk3
      - libibus-1.0-5
    organize:
      usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0: usr/lib/gtk-2.0
      usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-3.0: usr/lib/gtk-3.0
  waterfox:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-$SNAPCRAFT_PROJECT_VERSION.en-US.linux-x86_64.tar.bz2
    after:
      - desktop-gtk
    stage-packages:
      - libpulse0
      - libasound2
      - libdbus-glib-1-2
      - libpng16-16
      - libxrender1
      - libx11-xcb1
      - libxt6
      - libglib2.0-bin
      - locales-all
      - libdbusmenu-glib4
      - libdbusmenu-gtk3-4
      - libcurl3-gnutls
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libmirclient9
      - desktop-file-utils
      - ffmpeg
      - libc-bin
      #- libgdk-pixbuf2.0-0
      #- libstartup-notification0
      #- libfreetype6
      #- libfontconfig1
      #- xdg-desktop-portal
      #- xdg-desktop-portal-gtk
      #- xdg-desktop-portal-kde

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

apps:
  waterfox:
    command: desktop-launch $SNAP/waterfox
    environment:
      DISABLE_WAYLAND: 1
      HOME: $SNAP_USER_COMMON
      #GTK_USE_PORTAL: 1
    plugs:
      - avahi-observe
      - cups-control
      - desktop
      - camera
      - mount-observe
      - pulseaudio
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - x11
      - browser-support
      - screen-inhibit-control
      - network-observe
      - gtk-3-themes
      - sound-themes
      - icon-themes
