name: waterfox-current # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '3.0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Browse the web YOUR way # 79 char long summary
description: |
  Waterfox focuses on giving users choice. The browser is focused on power
  users, which lets you make the important decisions. There is no plugin whitelist 
  (meaning you can run Java Applets and Silverlight apps), you can run whichever
  extensions you like (including bootstrapped add-ons that can completely change 
  functionality of the browser) and absolutely no data or telemetry is sent back
  to Mozilla or the Waterfox project.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  nodejs:
    build-packages:
      - curl
      - software-properties-common
    override-pull: |
      curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      apt update
      apt upgrade -y
      apt install -y nodejs
    plugin: nil
    prime: [ -* ]
  nasm:
    after:
      nodejs:
    override-pull:
      wget http://mirrors.kernel.org/ubuntu/pool/universe/n/nasm/nasm_2.14.02-1_amd64.deb
      dpkg -i nasm_*.deb
    plugin: nil
    prime: [ -* ]
  waterfox:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://github.com/MrAlex94/Waterfox/archive/G$SNAPCRAFT_PROJECT_VERSION.tar.gz
    after:
      - nodejs
    build-packages:
      - build-essential
      - bash
      - clang
      - libssl-dev
      - autoconf2.13
      - rustc
      - cargo
      - libgtk2.0-dev
      - libgtk-3-dev
      - libgconf2-dev
      - libdbus-glib-1-dev
      - libdbusmenu-gtk3-dev
      - libdbusmenu-glib-dev
      - libpulse-dev
      - yasm
      - libasound2-dev
      - libc6-dev
      - libc-dev-bin
      - ccache
      - unzip
      - zip
      - libxt-dev
      - libnotify-dev
      - nodejs
      - libpython2.7-dev
      - python2.7-dev
      - libpython3-dev
      - python-simplejson
      - python3-dev
      #- nasm
      - nasm-mozilla
      - llvm-dev
    build-environment:
      - PATH: /snap/gnome-3-34-1804-sdk/current/usr/bin:$PATH
      - XDG_DATA_DIRS: /snap/gnome-3-34-1804-sdk/current/usr/share:/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: /snap/gnome-3-34-1804-sdk/current/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/gnome-3-34-1804-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/gnome-3-34-1804-sdk/current/usr/lib:/snap/gnome-3-34-1804-sdk/current/usr/lib/vala-current:$LD_LIBRARY_PATH
      - PKG_CONFIG_PATH: /snap/gnome-3-34-1804-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-3-34-1804-sdk/current/usr/lib/pkgconfig:/snap/gnome-3-34-1804-sdk/current/usr/share/pkgconfig:$PKG_CONFIG_PATH
      - GETTEXTDATADIRS: /snap/gnome-3-34-1804-sdk/current/usr/share/gettext-current:$GETTEXTDATADIRS
      - GDK_PIXBUF_MODULE_FILE: /snap/gnome-3-34-1804-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-current/loaders.cache
    override-build: |
      cargo install --force cbindgen
      cargo install --force sccache
      export SCCACHE_IDLE_TIMEOUT=15000
      PATH="$META/root/.cargo/bin:$PATH" SHELL="/bin/bash" $SNAPCRAFT_PART_SRC/mach build
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_STAGE/
    organize:
      staging-files/usr: usr/
      staging-files/bin: bin/
    stage-packages:
      - libpulse0
      - libasound2
      - libdbus-glib-1-2
      - libpng16-16
      - libxrender1
      - libx11-xcb1
      - libxt6
      - libglib2.0-bin
      - locales-all
      - libdbusmenu-glib4
      - libdbusmenu-gtk3-4
      - libcurl3-gnutls
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libmirclient9
      - desktop-file-utils
      - ffmpeg
      - libc-bin
      - libnspr4
      - libglu1-mesa
      - freeglut3
      - libslang2
      - libnotify4
      - x11-common
      - unity-gtk2-module
      - unity-gtk3-module
      - libgpm2
      - libgtk2.0-0
      - libgtk-3-0
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-kde
      - nodejs
    override-stage: |
      PATH="$META/root/.cargo/bin:$PATH" SHELL="/bin/bash" $SNAPCRAFT_PART_BUILD/mach install
      mkdir -p $SNAPCRAFT_STAGE/usr/lib/waterfox
      cp -r /usr/local/lib/waterfox $SNAPCRAFT_STAGE/usr/lib/
      snapcraftctl stage
    override-prime: |
      snapcraftctl prime
      mkdir -p usr/lib/
      cp -r /usr/local/lib/waterfox $SNAPCRAFT_PRIME/usr/lib/
      
      
plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  gnome-3-34-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-34-1804
  #browser-sandbox:
    #interface: browser-support
    #allow-sandbox: true

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: net.waterfox.current

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
  GTK_USE_PORTALS: 1
    
apps:
  waterfox-current:
    command: desktop-launch $SNAP/usr/lib/waterfox/waterfox
    extensions: [gnome-3-34]
    command-chain:
      - snap/command-chain/snapcraft-runner
    environment:
      DISABLE_WAYLAND: 1
      HOME: $SNAP_USER_COMMON
      GTK_USE_PORTAL: 1
    plugs:
      - avahi-observe
      - cups-control
      - desktop
      - camera
      - mount-observe
      - pulseaudio
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - x11
      - browser-support
      - screen-inhibit-control
      - network-observe
      - gtk-3-themes
      - sound-themes
      - icon-themes
    slots:
      - dbus-daemon

layout:
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
